services:
  - type: worker
    name: angel-xb-mafia
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 Angel.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
      - key: OWNER_USERNAME
        value: ZEXX
      - key: LOGGER_GROUP
        sync: false
      - key: START_IMG
        sync: false
      - key: UPI_ID
        sync: false
      - key: QR_LINK
        sync: false
      # --- INKO ADD KIYA HAI TAKI SCREEN PAR DIKHE ---
      - key: SUPPORT_CHAT
        sync: false
      - key: UPDATE_CHANNEL
        sync: false
